=== BobbyPanza/ExcelBOM/docs/CustomForm.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CustomForms" type="FormsList"/>
  <xs:complexType name="FormsList">
    <xs:sequence>
      <xs:element name="Form" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Caption" type="xs:string"/>
            <xs:element name="IconPath" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="RibbonGroup" type="xs:string"/>
            <xs:element name="DatabaseInfo">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Table" type="xs:string"/>
                  <xs:element name="Fields" type="FieldsList"/>
                  <xs:element name="Constraints" minOccurs="0" maxOccurs="1" type="ConstraintList"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="ToolbarInfo" minOccurs="0" maxOccurs="1" type="ToolbarList"/>
            <xs:element name="FilterInfo" minOccurs="0" maxOccurs="1" type="FilterRowList"/>
          </xs:sequence>
          <xs:attribute name="ShowImportButton" type="xs:boolean" use="optional"/>
          <xs:attribute name="ShowInsertButton" type="xs:boolean" use="optional"/>
          <xs:attribute name="ShowEditButton" type="xs:boolean" use="optional"/>
          <xs:attribute name="ShowDeleteButton" type="xs:boolean" use="optional"/>
          <xs:attribute name="ShowPrintButton" type="xs:boolean" use="optional"/>
          <xs:attribute name="GroupFooters" type="xs:nonNegativeInteger" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FieldsList">
    <xs:sequence>
      <xs:element name="Field" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Name" type="FieldName"/>
            <xs:element name="Caption" type="xs:string"/>
            <xs:element name="Type" type="FieldType"/>
            <xs:element name="SourceQuery" minOccurs="0" maxOccurs="1" type="xs:string"/>
          </xs:sequence>
          <xs:attribute name="ReadOnly" type="xs:boolean" use="optional"/>
          <xs:attribute name="UpdateAfterFileImport" type="xs:boolean" use="optional"/>
          <xs:attribute name="InKey" type="xs:boolean" use="optional"/>
          <xs:attribute name="InWhere" type="xs:boolean" use="optional"/>
          <xs:attribute name="InUpdate" type="xs:boolean" use="optional"/>
          <xs:attribute name="IsProgressive" type="xs:boolean" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConstraintList">
    <xs:sequence>
      <xs:element name="Unique" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="FieldName">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*.+\s*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FieldType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*((VARCHAR\(\d+\))|(INTEGER)|(SMALLINT)|(BIT)|(NUMERIC\(\d+,\d+\))|(DATE)|(DATETIME2\(6\))|(VARCHAR\(max\))|(IMAGEPATH)|(CHAR\(\d+\)))\s*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ToolbarList">
    <xs:sequence>
      <xs:element name="Toolbar" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Caption" type="xs:string"/>
            <xs:element name="ButtonInfo" type="ButtonList"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ButtonList">
    <xs:sequence>
      <xs:element name="Button" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Code" type="ButtonCode"/>
            <xs:element name="Caption" type="xs:string"/>
            <xs:element name="StoredProcedure" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Name" type="xs:string"/>
                  <xs:element name="ParameterInfo" type="ParameterList"/>
                </xs:sequence>
                <xs:attribute name="RefreshAfterExecution" type="xs:boolean" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="Application" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Name" type="xs:string"/>
                  <xs:element name="WorkingDirectory" type="xs:string"/>
                  <xs:element name="ParameterInfo" type="ParameterList"/>
                </xs:sequence>
                <xs:attribute name="RefreshAfterExecution" type="xs:boolean" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="WindowsOpen" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="ParameterInfo" type="ParameterList"/>
                </xs:sequence>
                <xs:attribute name="RefreshAfterExecution" type="xs:boolean" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="CustomForm" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Name" type="xs:string"/>
                  <xs:element name="FilterInputInfo" type="FilterInputList"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="DLLProcedure" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="LibName" type="xs:string"/>
                  <xs:element name="ProcName" type="xs:string"/>
                  <xs:element name="ProcCalling" type="ProcCallingValueList"/>
                  <xs:element name="ParameterInfo" type="ParameterList"/>
                </xs:sequence>
                <xs:attribute name="RefreshAfterExecution" type="xs:boolean" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="Type" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="ButtonCode">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*.+\s*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ProcCallingValueList">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*((STDCALL)|(CDECL))\s*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ParameterList">
    <xs:sequence>
      <xs:element name="Param" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Value" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="ParamType" minOccurs="0" maxOccurs="1" type="ParameterTypeList"/>
          </xs:sequence>
          <xs:attribute name="Type" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="ParameterTypeList">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*((STRING)|(SMALLINT)|(INTEGER)|(FLOAT)|(STRING)|(BOOL))\s*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="FilterRowList">
    <xs:sequence>
      <xs:element name="FilterRow" minOccurs="0" maxOccurs="unbounded" type="FilterList"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FilterList">
    <xs:sequence>
      <xs:element name="Filter" minOccurs="0" maxOccurs="unbounded" >
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Field" type="xs:string"/>
            <xs:element name="Caption" type="xs:string"/>
            <xs:element name="TrueValue" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="FalseValue" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="Query" type="xs:string" minOccurs="0" maxOccurs="1"/>
          </xs:sequence>
          <xs:attribute name="Type" type="xs:nonNegativeInteger" use="required"/>
          <xs:attribute name="MultiSelect" type="xs:boolean" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FilterInputList">
    <xs:sequence>
      <xs:element name="FilterInput" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>  
          <xs:sequence>
            <xs:element name="FilterField" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="FilterValueInfo" minOccurs="1" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Value" minOccurs="0" maxOccurs="1" type="xs:string"/>
                  <xs:element name="ValueFrom" minOccurs="0" maxOccurs="1" type="xs:string"/>
                  <xs:element name="ValueTo" minOccurs="0" maxOccurs="1" type="xs:string"/>
                </xs:sequence>
                 <xs:attribute name="Type" type="xs:nonNegativeInteger" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="Type" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== BobbyPanza/ExcelBOM/docs/ImportBom.CustomForms.xml
<?xml version="1.0" encoding="utf-8"?>
<CustomForms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="CustomForm.xsd">
  <Form ShowImportButton="false" ShowInsertButton="false" ShowEditButton="false" ShowDeleteButton="false" ShowPrintButton="false">
    <Caption>IBom - Run Log</Caption>
    <IconPath></IconPath>
    <RibbonGroup>Tecnologia</RibbonGroup>
    <DatabaseInfo>
      <Table>dbo.Xt_ImportBom_LogRun</Table>
      <Fields>
        <Field ReadOnly="true" InKey="true" InWhere="true" IsProgressive="true">
          <Name>IDRun</Name>
          <Caption>ID Run</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>DataOraInizio</Name>
          <Caption>Data Ora Inizio</Caption>
          <Type>DATETIME2(6)</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>DataOraFine</Name>
          <Caption>Data Ora Fine</Caption>
          <Type>DATETIME2(6)</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>IDHeader</Name>
          <Caption>ID Header</Caption>
          <Type>CHAR(36)</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>Stato</Name>
          <Caption>Stato</Caption>
          <Type>VARCHAR(20)</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>NumArticoli</Name>
          <Caption>Num. Articoli</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>NumInseriti</Name>
          <Caption>Num. Inseriti</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>NumAggiornati</Name>
          <Caption>Num. Aggiornati</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>NumErrori</Name>
          <Caption>Num. Errori</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>Messaggio</Name>
          <Caption>Messaggio</Caption>
          <Type>VARCHAR(max)</Type>
        </Field>
      </Fields>
    </DatabaseInfo>
    <FilterInfo>
      <FilterRow>
        <Filter Type="2">
          <Field>Stato</Field>
          <Caption>Stato</Caption>
        </Filter>
        <Filter Type="2">
          <Field>IDHeader</Field>
          <Caption>ID Header</Caption>
        </Filter>
      </FilterRow>
      <FilterRow>
        <Filter Type="3">
          <Field>DataOraInizio</Field>
          <Caption>Data Inizio</Caption>
        </Filter>
        <Filter Type="4">
          <Field>NumErrori</Field>
          <Caption>Num. Errori</Caption>
        </Filter>
      </FilterRow>
    </FilterInfo>
  </Form>

  <Form ShowImportButton="false" ShowInsertButton="false" ShowEditButton="false" ShowDeleteButton="false" ShowPrintButton="false">
    <Caption>IBom - Articoli Log</Caption>
    <IconPath></IconPath>
    <RibbonGroup>Tecnologia</RibbonGroup>
    <DatabaseInfo>
      <Table>dbo.Xt_ImportBom_LogArt</Table>
      <Fields>
        <Field ReadOnly="true" InKey="true" InWhere="true" IsProgressive="true">
          <Name>IDLog</Name>
          <Caption>ID Log</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field ReadOnly="true" InWhere="true">
          <Name>IDRun</Name>
          <Caption>ID Run</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>DataOra</Name>
          <Caption>Data Ora</Caption>
          <Type>DATETIME2(6)</Type>
        </Field>
        <Field ReadOnly="true" InWhere="true">
          <Name>PartCode</Name>
          <Caption>Codice Articolo</Caption>
          <Type>VARCHAR(20)</Type>
        </Field>
        <Field ReadOnly="true" InWhere="true">
          <Name>FMCOD</Name>
          <Caption>Famiglia</Caption>
          <Type>VARCHAR(15)</Type>
        </Field>
        <Field ReadOnly="true" InWhere="true">
          <Name>Azione</Name>
          <Caption>Azione</Caption>
          <Type>VARCHAR(10)</Type>
        </Field>
        <Field ReadOnly="true" InWhere="true">
          <Name>Esito</Name>
          <Caption>Esito</Caption>
          <Type>VARCHAR(10)</Type>
        </Field>
        <Field ReadOnly="true">
          <Name>Messaggio</Name>
          <Caption>Messaggio</Caption>
          <Type>VARCHAR(max)</Type>
        </Field>
      </Fields>
    </DatabaseInfo>
    <FilterInfo>
      <FilterRow>
        <Filter Type="4">
          <Field>IDRun</Field>
          <Caption>ID Run</Caption>
        </Filter>
        <Filter Type="2">
          <Field>PartCode</Field>
          <Caption>Codice Articolo</Caption>
        </Filter>
      </FilterRow>
      <FilterRow>
        <Filter Type="2">
          <Field>Azione</Field>
          <Caption>Azione</Caption>
        </Filter>
        <Filter Type="2">
          <Field>Esito</Field>
          <Caption>Esito</Caption>
        </Filter>
      </FilterRow>
      <FilterRow>
        <Filter Type="2">
          <Field>FMCOD</Field>
          <Caption>Famiglia</Caption>
        </Filter>
        <Filter Type="3">
          <Field>DataOra</Field>
          <Caption>Data Ora</Caption>
        </Filter>
      </FilterRow>
    </FilterInfo>
  </Form>

  <Form ShowImportButton="false" ShowInsertButton="true" ShowEditButton="true" ShowDeleteButton="true" ShowPrintButton="false">
    <Caption>IBom - Mappings</Caption>
    <IconPath></IconPath>
    <RibbonGroup>Tecnologia</RibbonGroup>
    <DatabaseInfo>
      <Table>dbo.Xt_ImportBom_Mappings</Table>
      <Fields>
        <Field ReadOnly="true" InKey="true" InWhere="true" IsProgressive="true">
          <Name>IDMapping</Name>
          <Caption>ID Mapping</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field InWhere="true" InUpdate="false">
          <Name>Ambito</Name>
          <Caption>Ambito</Caption>
          <Type>VARCHAR(50)</Type>
        </Field>
        <Field InWhere="true" InUpdate="false">
          <Name>CodiceSource</Name>
          <Caption>Codice Source</Caption>
          <Type>VARCHAR(100)</Type>
        </Field>
        <Field InUpdate="true">
          <Name>CodiceTarget</Name>
          <Caption>Codice Target</Caption>
          <Type>VARCHAR(100)</Type>
        </Field>
        <Field InUpdate="true">
          <Name>Descrizione</Name>
          <Caption>Descrizione</Caption>
          <Type>VARCHAR(200)</Type>
        </Field>
      </Fields>
      <Constraints>
        <Unique>Ambito,CodiceSource</Unique>
      </Constraints>
    </DatabaseInfo>
    <FilterInfo>
      <FilterRow>
        <Filter Type="5" MultiSelect="true">
          <Field>Ambito</Field>
          <Caption>Ambito</Caption>
          <Query>SELECT DISTINCT Ambito, Ambito, Ambito FROM dbo.Xt_ImportBom_Mappings ORDER BY Ambito</Query>
        </Filter>
        <Filter Type="2">
          <Field>CodiceSource</Field>
          <Caption>Codice Source</Caption>
        </Filter>
      </FilterRow>
      <FilterRow>
        <Filter Type="2">
          <Field>CodiceTarget</Field>
          <Caption>Codice Target</Caption>
        </Filter>
        <Filter Type="2">
          <Field>Descrizione</Field>
          <Caption>Descrizione</Caption>
        </Filter>
      </FilterRow>
    </FilterInfo>
  </Form>

  <Form ShowImportButton="false" ShowInsertButton="true" ShowEditButton="true" ShowDeleteButton="true" ShowPrintButton="false">
    <Caption>IBom - Config</Caption>
    <IconPath></IconPath>
    <RibbonGroup>Tecnologia</RibbonGroup>
    <DatabaseInfo>
      <Table>dbo.Xt_ImportBom_Config</Table>
      <Fields>
        <Field ReadOnly="true" InKey="true" InWhere="true" IsProgressive="true">
          <Name>IDConfig</Name>
          <Caption>ID Config</Caption>
          <Type>INTEGER</Type>
        </Field>
        <Field InWhere="true" InUpdate="false">
          <Name>Chiave</Name>
          <Caption>Chiave</Caption>
          <Type>VARCHAR(100)</Type>
        </Field>
        <Field InUpdate="true">
          <Name>Valore</Name>
          <Caption>Valore</Caption>
          <Type>VARCHAR(500)</Type>
        </Field>
        <Field InUpdate="true">
          <Name>Descrizione</Name>
          <Caption>Descrizione</Caption>
          <Type>VARCHAR(200)</Type>
        </Field>
      </Fields>
      <Constraints>
        <Unique>Chiave</Unique>
      </Constraints>
    </DatabaseInfo>
    <FilterInfo>
      <FilterRow>
        <Filter Type="2">
          <Field>Chiave</Field>
          <Caption>Chiave</Caption>
        </Filter>
        <Filter Type="2">
          <Field>Valore</Field>
          <Caption>Valore</Caption>
        </Filter>
      </FilterRow>
      <FilterRow>
        <Filter Type="2">
          <Field>Descrizione</Field>
          <Caption>Descrizione</Caption>
        </Filter>
      </FilterRow>
    </FilterInfo>
  </Form>
</CustomForms>
